# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


dayone_one = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.1.jpg", title: "", description: ""})
dayone_two = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.2.jpg", title: "", description: ""})
dayone_three = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.3.jpg", title: "", description: ""})

daytwo_one = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.1.jpg", title: "", description: ""})
daytwo_two = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.2.jpg", title: "", description: ""})
daytwo_three = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.3.jpg", title: "", description: ""})
daytwo_four = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.4.jpg", title: "", description: ""})

daythree_one = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.1.jpg", title: "", description: ""})
daythree_two = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.2.jpg", title: "", description: ""})
daythree_three = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.3.jpg", title: "", description: ""})
daythree_four = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.4.jpg", title: "", description: ""})
daythree_five = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.5.jpg", title: "", description: ""})
daythree_six = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.6.jpg", title: "", description: ""})
daythree_seven = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.7.jpg", title: "", description: ""})
daythree_eight = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.8.jpg", title: "", description: ""})
daythree_nine = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.9.jpg", title: "", description: ""})
daythree_ten = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.10.jpg", title: "", description: ""})
daythree_eleven = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.11.jpg", title: "", description: ""})
daythree_twelve = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.12.jpg", title: "", description: ""})
daythree_thirteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.13.jpg", title: "", description: ""})
daythree_fourteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.14.jpg", title: "", description: ""})
daythree_fifteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.15.jpg", title: "", description: ""})
daythree_sixteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.16.jpg", title: "", description: ""})
daythree_seventeen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.17.jpg", title: "", description: ""})
daythree_eighteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.18.jpg", title: "", description: ""})
daythree_nineteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.19.jpg", title: "", description: ""})

dayfour_one = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.1.jpg", title: "", description: ""})
dayfour_two = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.2.jpg", title: "", description: ""})
dayfour_three = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.3.jpg", title: "", description: ""})
dayfour_four = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.4.jpg", title: "", description: ""})
dayfour_five = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.5.jpg", title: "", description: ""})
dayfour_six = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.6.jpg", title: "", description: ""})
dayfour_seven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.7.jpg", title: "", description: ""})
dayfour_eight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.8.jpg", title: "", description: ""})
dayfour_nine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.9.jpg", title: "", description: ""})
dayfour_ten = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.10.jpg", title: "", description: ""})
dayfour_eleven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.11.jpg", title: "", description: ""})
dayfour_twelve = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.12.jpg", title: "", description: ""})
dayfour_thirteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.13.jpg", title: "", description: ""})
dayfour_fourteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.14.jpg", title: "", description: ""})
dayfour_fifteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.15.jpg", title: "", description: ""})
dayfour_sixteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.16.jpg", title: "", description: ""})
dayfour_seventeen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.17.jpg", title: "", description: ""})
dayfour_eighteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.18.jpg", title: "", description: ""})
dayfour_nineteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.19.jpg", title: "", description: ""})
dayfour_twenty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.20.jpg", title: "", description: ""})
dayfour_tone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.21.jpg", title: "", description: ""})
dayfour_ttwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.22.jpg", title: "", description: ""})
dayfour_tthree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.23.jpg", title: "", description: ""})
dayfour_tfour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.24.jpg", title: "", description: ""})
dayfour_tfive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.25.jpg", title: "", description: ""})
dayfour_tsix = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.26.jpg", title: "", description: ""})
dayfour_tseven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.27.jpg", title: "", description: ""})
dayfour_teight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.28.jpg", title: "", description: ""})
dayfour_tnine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.29.jpg", title: "", description: ""})
dayfour_thirty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.30.jpg", title: "", description: ""})
dayfour_thone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.31.jpg", title: "", description: ""})
dayfour_thtwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.32.jpg", title: "", description: ""})
dayfour_ththree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.33.jpg", title: "", description: ""})
dayfour_thfour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.34.jpg", title: "", description: ""})
dayfour_thfive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.35.jpg", title: "", description: ""})
dayfour_thsix = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.36.jpg", title: "", description: ""})
dayfour_thseven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.37.jpg", title: "", description: ""})
dayfour_theight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.38.jpg", title: "", description: ""})
dayfour_thnine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.39.jpg", title: "", description: ""})
dayfour_forty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.40.jpg", title: "", description: ""})
dayfour_fone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.41.jpg", title: "", description: ""})
dayfour_ftwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.42.jpg", title: "", description: ""})
dayfour_fthree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.43.jpg", title: "", description: ""})
dayfour_ffour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.44.jpg", title: "", description: ""})
dayfour_ffive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.45.jpg", title: "", description: ""})

dayfive_one = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.1.jpg", title: "", description: ""})
dayfive_two = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.2.jpg", title: "", description: ""})
dayfive_three = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.3.jpg", title: "", description: ""})
dayfive_four = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.4.jpg", title: "", description: ""})
dayfive_five = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.5.jpg", title: "", description: ""})
dayfive_six = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.6.jpg", title: "", description: ""})
dayfive_seven = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.7.jpg", title: "", description: ""})
dayfive_eight = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.8.jpg", title: "", description: ""})
dayfive_nine = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.9.jpg", title: "", description: ""})
dayfive_ten = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.10.jpg", title: "", description: ""})
dayfive_eleven = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.11.jpg", title: "", description: ""})
dayfive_twelve = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.12.jpg", title: "", description: ""})
dayfive_thirteen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.13.jpg", title: "", description: ""})
dayfive_fourteen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.14.jpg", title: "", description: ""})
dayfive_fifteen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.15.jpg", title: "", description: ""})
dayfive_sixteen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.16.jpg", title: "", description: ""})
dayfive_seventeen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.17.jpg", title: "", description: ""})
dayfive_eighteen = Dayfive.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfive/5.18.jpg", title: "", description: ""})

video_one = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/1.mp4", title: "", description: ""})
video_two = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/2.mp4", title: "", description: ""})
video_three = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/3.mp4", title: "", description: ""})
video_four = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/4.mp4", title: "", description: ""})
video_five = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/5.mp4", title: "", description: ""})
video_six = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/6.mp4", title: "", description: ""})
video_seven = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/7.mp4", title: "", description: ""})
video_eight = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/8.mp4", title: "", description: ""})
video_nine = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/9.mp4", title: "", description: ""})
video_ten = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/10.mp4", title: "", description: ""})
video_eleven = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/11.mp4", title: "", description: ""})
video_twelve = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/12.mp4", title: "", description: ""})
video_thirteen = Video.create({ video: "https://s3.amazonaws.com/josemaria-triptousa/videos/13.mp4", title: "", description: ""})

daysix_one = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.1.jpg", title: "", description: ""})
daysix_two = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.2.jpg", title: "", description: ""})
daysix_three = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.3.jpg", title: "", description: ""})
daysix_four = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.4.jpg", title: "", description: ""})
daysix_five = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.5.jpg", title: "", description: ""})
daysix_six = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.6.jpg", title: "", description: ""})
daysix_seven = Daysix.create({ picture: "https://s3.amazonaws.com/josemaria-triptousa/daysix/6.7.jpg", title: "", description: ""})
