# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


dayone_one = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.1.jpg", title: "", description: ""})
dayone_two = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.2.jpg", title: "", description: ""})
dayone_three = Dayone.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayone/1.3.jpg", title: "", description: ""})

daytwo_one = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.1.jpg", title: "", description: ""})
daytwo_two = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.2.jpg", title: "", description: ""})
daytwo_three = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.3.jpg", title: "", description: ""})
daytwo_four = Daytwo.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daytwo/2.4.jpg", title: "", description: ""})

daythree_one = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.1.jpg", title: "", description: ""})
daythree_two = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.2.jpg", title: "", description: ""})
daythree_three = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.3.jpg", title: "", description: ""})
daythree_four = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.4.jpg", title: "", description: ""})
daythree_five = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.5.jpg", title: "", description: ""})
daythree_six = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.6.jpg", title: "", description: ""})
daythree_seven = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.7.jpg", title: "", description: ""})
daythree_eight = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.8.jpg", title: "", description: ""})
daythree_nine = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.9.jpg", title: "", description: ""})
daythree_ten = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.10.jpg", title: "", description: ""})
daythree_eleven = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.11.jpg", title: "", description: ""})
daythree_twelve = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.12.jpg", title: "", description: ""})
daythree_thirteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.13.jpg", title: "", description: ""})
daythree_fourteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.14.jpg", title: "", description: ""})
daythree_fifteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.15.jpg", title: "", description: ""})
daythree_sixteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.16.jpg", title: "", description: ""})
daythree_seventeen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.17.jpg", title: "", description: ""})
daythree_eighteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.18.jpg", title: "", description: ""})
daythree_nineteen = Daythree.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/daythree/3.19.jpg", title: "", description: ""})

dayfour_one = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.1.jpg", title: "", description: ""})
dayfour_two = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.2.jpg", title: "", description: ""})
dayfour_three = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.3.jpg", title: "", description: ""})
dayfour_four = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.4.jpg", title: "", description: ""})
dayfour_five = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.5.jpg", title: "", description: ""})
dayfour_six = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.6.jpg", title: "", description: ""})
dayfour_seven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.7.jpg", title: "", description: ""})
dayfour_eight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.8.jpg", title: "", description: ""})
dayfour_nine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.9.jpg", title: "", description: ""})
dayfour_ten = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.10.jpg", title: "", description: ""})
dayfour_eleven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.11.jpg", title: "", description: ""})
dayfour_twelve = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.12.jpg", title: "", description: ""})
dayfour_thirteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.13.jpg", title: "", description: ""})
dayfour_fourteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.14.jpg", title: "", description: ""})
dayfour_fifteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.15.jpg", title: "", description: ""})
dayfour_sixteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.16.jpg", title: "", description: ""})
dayfour_seventeen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.17.jpg", title: "", description: ""})
dayfour_eighteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.18.jpg", title: "", description: ""})
dayfour_nineteen = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.19.jpg", title: "", description: ""})
dayfour_twenty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.20.jpg", title: "", description: ""})
dayfour_tone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.21.jpg", title: "", description: ""})
dayfour_ttwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.22.jpg", title: "", description: ""})
dayfour_tthree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.23.jpg", title: "", description: ""})
dayfour_tfour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.24.jpg", title: "", description: ""})
dayfour_tfive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.25.jpg", title: "", description: ""})
dayfour_tsix = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.26.jpg", title: "", description: ""})
dayfour_tseven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.27.jpg", title: "", description: ""})
dayfour_teight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.28.jpg", title: "", description: ""})
dayfour_tnine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.29.jpg", title: "", description: ""})
dayfour_thirty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.30.jpg", title: "", description: ""})
dayfour_thone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.31.jpg", title: "", description: ""})
dayfour_thtwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.32.jpg", title: "", description: ""})
dayfour_ththree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.33.jpg", title: "", description: ""})
dayfour_thfour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.34.jpg", title: "", description: ""})
dayfour_thfive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.35.jpg", title: "", description: ""})
dayfour_thsix = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.36.jpg", title: "", description: ""})
dayfour_thseven = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.37.jpg", title: "", description: ""})
dayfour_theight = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.38.jpg", title: "", description: ""})
dayfour_thnine = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.39.jpg", title: "", description: ""})
dayfour_forty = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.40.jpg", title: "", description: ""})
dayfour_fone = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.41.jpg", title: "", description: ""})
dayfour_ftwo = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.42.jpg", title: "", description: ""})
dayfour_fthree = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.43.jpg", title: "", description: ""})
dayfour_ffour = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.44.jpg", title: "", description: ""})
dayfour_ffive = Dayfour.create({ picture: "https://s3.amazonaws.com/patri-website/JoseMaria/dayfour/4.45.jpg", title: "", description: ""})
